// design-sync scaffolding generator for tahi-dashboard.
//
// tahi-dashboard is a Next.js app, not a published component library, so the
// converter runs in "package" shape with an explicit barrel --entry that
// re-exports ONLY the curated design-system primitives (the set showcased in
// app/(dashboard)/design-system/design-system-content.tsx). This keeps the
// esbuild IIFE bundle decoupled from the app's server/Next/Clerk code.
//
// Regenerate after editing the manifest below:  node .design-sync/setup.mjs
// (Also run  node .design-sync/compile-css.mjs  to refresh compiled.css.)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const REPO = process.cwd()
const DS = join(REPO, '.design-sync')
for (const d of ['stubs', 'groups', 'docs', 'previews']) mkdirSync(join(DS, d), { recursive: true })

// ── Manifest: [ComponentName, sourceFile(in components/tahi), group] ────────
// Export names verified against the import block of design-system-content.tsx
// (lines 5-40) + toast.tsx (ToastProvider).
const M = [
  // Brand marks
  ['LeafGlyph', 'tahi-glyphs', 'brand'],
  ['LeafIcon', 'tahi-glyphs', 'brand'],
  ['TahiWordmark', 'tahi-glyphs', 'brand'],
  ['TahiStudioWordmark', 'tahi-glyphs', 'brand'],
  ['TahiIconMark', 'tahi-glyphs', 'brand'],
  // Animated icons
  ['AnimatedSettings', 'animated-icons', 'icons'],
  ['AnimatedBell', 'animated-icons', 'icons'],
  ['AnimatedHeart', 'animated-icons', 'icons'],
  ['AnimatedRefresh', 'animated-icons', 'icons'],
  ['AnimatedSearch', 'animated-icons', 'icons'],
  ['AnimatedEye', 'animated-icons', 'icons'],
  ['AnimatedSparkles', 'animated-icons', 'icons'],
  ['AnimatedCheckCircle', 'animated-icons', 'icons'],
  ['AnimatedTrash', 'animated-icons', 'icons'],
  // Primitives
  ['TahiButton', 'tahi-button', 'primitives'],
  ['TahiLink', 'tahi-button', 'primitives'],
  ['Avatar', 'avatar', 'primitives'],
  ['Badge', 'badge', 'primitives'],
  ['Card', 'card', 'primitives'],
  ['Tooltip', 'tooltip', 'primitives'],
  ['Callout', 'callout', 'primitives'],
  ['ProgressBar', 'progress-bar', 'primitives'],
  ['Stepper', 'stepper', 'primitives'],
  ['KPICard', 'kpi-card', 'primitives'],
  ['FeatureCard', 'feature-card', 'primitives'],
  ['Menu', 'menu', 'primitives'],
  ['SlideOver', 'slide-over', 'primitives'],
  ['ToastProvider', 'toast', 'primitives'],
  // Charts
  ['BarChart', 'chart', 'charts'],
  ['LineChart', 'chart', 'charts'],
  ['Sparkline', 'chart', 'charts'],
  ['Gauge', 'chart', 'charts'],
  ['DonutChart', 'chart', 'charts'],
  ['GanttChart', 'chart', 'charts'],
  ['FunnelChart', 'chart', 'charts'],
  ['MultiBarChart', 'chart', 'charts'],
  ['Heatmap', 'chart', 'charts'],
  ['CalendarHeatmap', 'chart', 'charts'],
  // Data
  ['DataTable', 'data-table', 'data'],
  ['FilterBar', 'filter-bar', 'data'],
  // Messaging
  ['MessageBubble', 'message-bubble', 'messaging'],
  ['MessageThread', 'message-thread', 'messaging'],
  ['Composer', 'composer', 'messaging'],
  ['FileAttachmentList', 'file-attachment-list', 'messaging'],
  // Boards
  ['KanbanBoard', 'kanban-board', 'boards'],
  ['BoardView', 'board-view', 'boards'],
]

// Non-component exports to also surface on window.TahiDS (helpers used by
// previews / the design agent). Keyed by source file.
const EXTRA = {
  badge: ['statusTone', 'priorityTone'],
  toast: ['useToast'],
}

// Family files hold many small exports sharing one header doc — let their
// prompt synthesize from props + authored preview examples instead of pasting
// the shared header onto every sibling.
const FAMILY_FILES = new Set(['chart', 'tahi-glyphs', 'animated-icons'])

// ── Barrel entry ────────────────────────────────────────────────────────────
const byFile = new Map()
for (const [name, file] of M) {
  if (!byFile.has(file)) byFile.set(file, [])
  byFile.get(file).push(name)
}
let barrel =
  '// AUTO-GENERATED by .design-sync/setup.mjs — DS bundle entry (curated primitives).\n' +
  '// Re-exports only the design-system components from components/tahi/* so esbuild\n' +
  '// produces a clean, app-decoupled IIFE. Do not edit by hand; edit setup.mjs.\n\n'
for (const [file, names] of byFile) {
  const all = [...names, ...(EXTRA[file] ?? [])]
  barrel += `export { ${all.join(', ')} } from '@/components/tahi/${file}'\n`
}
writeFileSync(join(DS, 'ds-entry.tsx'), barrel)

// ── Next.js stubs (neutralize next/link, next/image, next/navigation) ───────
writeFileSync(join(DS, 'stubs', 'next-link.tsx'),
`import * as React from 'react'

type LinkProps = Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
  href?: string | { pathname?: string }
  prefetch?: boolean
  replace?: boolean
  scroll?: boolean
  shallow?: boolean
  passHref?: boolean
  locale?: string | false
  legacyBehavior?: boolean
}

const Link = React.forwardRef<HTMLAnchorElement, LinkProps>(function Link(
  { href, prefetch, replace, scroll, shallow, passHref, locale, legacyBehavior, children, ...rest },
  ref,
) {
  const h = typeof href === 'string' ? href : href?.pathname ?? '#'
  return <a ref={ref} href={h} {...rest}>{children}</a>
})

export default Link
`)

writeFileSync(join(DS, 'stubs', 'next-image.tsx'),
`import * as React from 'react'

type ImageProps = Omit<React.ImgHTMLAttributes<HTMLImageElement>, 'src'> & {
  src: string | { src: string }
  fill?: boolean
  priority?: boolean
  quality?: number
  placeholder?: string
  blurDataURL?: string
  loader?: unknown
  unoptimized?: boolean
}

const Image = React.forwardRef<HTMLImageElement, ImageProps>(function Image(
  { src, fill, priority, quality, placeholder, blurDataURL, loader, unoptimized, style, ...rest },
  ref,
) {
  const s = typeof src === 'string' ? src : src?.src
  const st: React.CSSProperties = fill
    ? { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', ...style }
    : (style ?? {})
  return <img ref={ref} src={s} style={st} {...rest} />
})

export default Image
`)

writeFileSync(join(DS, 'stubs', 'next-navigation.ts'),
`// Inert next/navigation stub for static design-system rendering.
export function usePathname(): string { return '/' }
export function useRouter() {
  return { push() {}, replace() {}, back() {}, forward() {}, refresh() {}, prefetch() {} }
}
export function useSearchParams(): URLSearchParams { return new URLSearchParams() }
export function useParams(): Record<string, string> { return {} }
export function useSelectedLayoutSegment(): string | null { return null }
export function useSelectedLayoutSegments(): string[] { return [] }
export function redirect(): never { throw new Error('redirect (stub)') }
export function notFound(): never { throw new Error('notFound (stub)') }
`)

// ── Build tsconfig (esbuild path resolution for @/* + next stubs) ───────────
writeFileSync(join(REPO, 'tsconfig.dssync.json'),
  JSON.stringify({
    compilerOptions: {
      baseUrl: '.',
      paths: {
        '@/*': ['./*'],
        'next/link': ['./.design-sync/stubs/next-link.tsx'],
        'next/image': ['./.design-sync/stubs/next-image.tsx'],
        'next/navigation': ['./.design-sync/stubs/next-navigation.ts'],
      },
    },
  }, null, 2) + '\n')

// ── Per-component doc files (group frontmatter + extracted header JSDoc) ─────
function extractTopJsdoc(src) {
  const m = /\/\*\*([\s\S]*?)\*\//.exec(src)
  if (!m) return ''
  return m[1].split('\n').map((l) => l.replace(/^\s*\*\s?/, '')).join('\n').trim()
}
const componentSrcMap = {}
const docsMap = {}
const srcCache = new Map()
for (const [name, file, group] of M) {
  componentSrcMap[name] = `components/tahi/${file}.tsx`
  const rel = `.design-sync/docs/${name}.md`
  docsMap[name] = rel
  let body = ''
  if (!FAMILY_FILES.has(file)) {
    if (!srcCache.has(file)) srcCache.set(file, readFileSync(join(REPO, 'components', 'tahi', `${file}.tsx`), 'utf8'))
    body = extractTopJsdoc(srcCache.get(file))
  }
  const fm = `---\ncategory: ${group}\n---\n`
  writeFileSync(join(REPO, rel), body ? `${fm}\n${body}\n` : fm)
}

// ── design-sync.config.json ─────────────────────────────────────────────────
const config = {
  pkg: 'tahi-dashboard',
  globalName: 'TahiDS',
  shape: 'package',
  projectId: '5d0df77c-458f-4199-bfc0-36d3290ddb48',
  entry: '.design-sync/ds-entry.tsx',
  srcDir: 'components/tahi',
  tsconfig: 'tsconfig.dssync.json',
  cssEntry: '.design-sync/compiled.css',
  runtimeFontPrefixes: ['Manrope'],
  componentSrcMap,
  docsMap,
  // Per-component card overrides:
  //  - wide components get a larger capture viewport so no column clips;
  //  - position:fixed overlays (SlideOver drawer, toast) use cardMode:single,
  //    which makes the card the containing block so the REAL component renders
  //    inside the card instead of escaping to the page viewport.
  overrides: {
    DataTable: { viewport: '900x560' },
    KanbanBoard: { viewport: '940x560' },
    BoardView: { viewport: '940x640' },
    SlideOver: { cardMode: 'single', viewport: '560x680', primaryStory: 'LiveOpenPanel' },
    ToastProvider: { cardMode: 'single', viewport: '420x240', primaryStory: 'ToastSuccess' },
  },
}
writeFileSync(join(REPO, 'design-sync.config.json'), JSON.stringify(config, null, 2) + '\n')

// ── Summary ─────────────────────────────────────────────────────────────────
const groups = {}
for (const [, , g] of M) groups[g] = (groups[g] ?? 0) + 1
console.log(`Generated scaffolding for ${M.length} components across ${byFile.size} source files.`)
console.log('Groups:', Object.entries(groups).map(([g, n]) => `${g}=${n}`).join(', '))
console.log('Wrote: .design-sync/ds-entry.tsx, stubs/, docs/ (' + M.length + '), tsconfig.dssync.json, design-sync.config.json')
