-- Migration 0097: the services catalogue learns who it belongs to
--
--   services.org_id
--     NULL = a global catalogue row, visible to every client. Set = private to
--     that one organisation. NULL is the default and the state of every
--     existing row, so nothing changes for anything already there.
--   services.visibility
--     'public' | 'hidden'. NOT NULL DEFAULT 'public'. A hidden row never
--     reaches the portal, even when it is global. The kill switch.
--
-- Why this exists. app/api/portal/services/route.ts served every
-- show_in_catalog = 1 row to every client, because there was nothing on the
-- table to scope by. That was survivable while the catalogue was eight generic
-- lines the studio wrote itself. It stops being survivable the moment the
-- ManyRequests import runs: 18 source services land here, several of them
-- named for the client they were priced for ("Glasswall Custom Retainer",
-- "Elevate custom hourly"), and without org_id every client would read every
-- other client's retainer name off their own Services page. The same column is
-- what finally lets a per-client retainer be modelled at all, which is the
-- other half of CT.11.
--
-- Two columns, not one, because they answer different questions. org_id
-- answers WHO may see this. visibility answers WHETHER anyone may. A row can
-- be private to Glasswall and still hidden while it is being written.
--
-- visibility is deliberately a second flag next to the existing
-- show_in_catalog integer rather than a replacement for it. show_in_catalog is
-- what the ManyRequests importer writes: lib/import/manyrequests/plan.ts
-- inserts all 18 source rows with show_in_catalog = 0 on purpose, because only
-- three are is_for_sale upstream and the client catalogue is a separate
-- decision. Dropping or repurposing that flag would fight the importer.
-- The portal requires BOTH (show_in_catalog = 1 AND visibility = 'public'), so
-- the answer to "can a client see this" fails closed on either one.
--
-- No REFERENCES clause on org_id, matching subscriptions.billed_contact_id.
-- The import writes rows for organisations that may later be archived, and a
-- cascade that silently deleted a priced catalogue row is a worse outcome than
-- a dangling id. SQLite also cannot add a real foreign key to an existing
-- table without rebuilding it.
--
-- NO BACKFILL, and that is the safe direction. Every existing row keeps
-- org_id NULL (global) and takes visibility 'public', so the catalogue that is
-- live today reads exactly as it does today. Narrowing a row to one client is
-- a decision the studio makes per row in the services editor.
--
-- ALTER TABLE ADD COLUMN cannot use IF NOT EXISTS in SQLite; the runtime
-- runner (app/api/admin/db/migrate) swallows the "duplicate column name"
-- error so re-running is safe. The index is IF NOT EXISTS in its own right.
-- A NOT NULL ADD COLUMN is legal here only because it carries a constant
-- DEFAULT, which SQLite applies to every existing row.
--
-- MERGE ORDER, NOT OPTIONAL. Apply this to staging and then production D1
-- BEFORE the code that references the columns is deployed, not after. Drizzle
-- expands a bare .select() into an explicit column list from db/schema.ts, so
-- from the moment the new schema ships the studio services list
-- (app/api/admin/services/route.ts, the one bare select on this table) fails
-- with "no such column: org_id", the portal names both columns in its WHERE,
-- and the ManyRequests cleanup counts services.org_id when it states a hard
-- delete's blast radius. The global search and the importer name their columns
-- and survive either ordering. The columns are additive, so applying them
-- AHEAD of the deploy is harmless to the running code: nothing reads them yet.
--
-- The runtime runner (POST /api/admin/db/migrate) cannot go first: the "0097"
-- entry lives in app/api/admin/db/migrate/route.ts and does not exist until
-- that deploy lands, so calling it beforehand answers 400 Unknown migration.
-- Apply the file directly with wrangler instead. wrangler.json carries both
-- database ids (staging b91cd27f, production 3bfa4848), so the names below
-- resolve without any extra flags:
--   1. wrangler d1 execute tahi-db-staging --remote --file=drizzle/migrations/0097_services_org_scope.sql
--   2. deploy, then smoke /services and the portal Services page in that order
--   3. wrangler d1 execute tahi-db --remote --file=drizzle/migrations/0097_services_org_scope.sql
--   4. approve the production deploy, then smoke the same two pages
--
-- POST /api/admin/db/migrate {"name":"0097"} is the after-the-fact fallback,
-- usable once the deploy that carries the entry is live.
ALTER TABLE services ADD COLUMN org_id text;
ALTER TABLE services ADD COLUMN visibility text NOT NULL DEFAULT 'public';
CREATE INDEX IF NOT EXISTS idx_services_org ON services(org_id);
