/**
 * SEO signals — pulls live GSC + GA4 + (optional) SE Ranking data
 * for a single topic, returns a structured competitive intel block
 * the writer/reviewer pipeline can feed into prompts.
 *
 * Used by:
 *   - generateGlossaryEntry (writer brief)
 *   - boost-bad-glossary cron (sort + queue underperformers)
 *   - reverse-engineer-indexing cron (find unindexed + IndexNow ping)
 *
 * Gracefully degrades when any source is unavailable — returns the
 * signals it could fetch and notes which ones it couldn't. Never
 * throws on a missing connection (returns empty signals object).
 */

import type { db } from '@/lib/db'
import {
  getGoogleAccessToken, listGscSites, resolveGscPropertyForUrl,
  searchAnalytics, inspectUrl, runGa4Report,
} from '@/lib/google'
import { schema } from '@/db/d1'
import { eq, inArray } from 'drizzle-orm'

type Database = Awaited<ReturnType<typeof db>>

export interface SeoSignals {
  topic: string
  url: string | null                 // current URL on tahi.studio, null if not yet published

  // Google Search Console (last 30 days, this URL specifically)
  gsc: {
    available: boolean
    clicks7d: number | null
    impressions7d: number | null
    avgPosition7d: number | null
    clicks30d: number | null
    impressions30d: number | null
    avgPosition30d: number | null
    indexStatus: string | null       // INDEXING_ALLOWED | BLOCKED_BY_ROBOTS_TXT | NOT_INDEXED | etc.
    lastCrawlTime: string | null
    topQueries: Array<{ query: string; clicks: number; impressions: number; position: number }>
  }

  // Google Analytics 4 (last 30 days, this URL pageview-level)
  ga4: {
    available: boolean
    sessions30d: number | null
    engagedSessions30d: number | null
    avgSessionDuration: number | null
  }

  // SE Ranking optional
  seRanking: {
    available: boolean
    targetKeyword: string | null
    currentPosition: number | null
    searchVolume: number | null
    difficulty: number | null
    competitorTopUrls: Array<{ url: string; title: string }>
    note: string
  }

  // Generated by us — readable brief for the writer
  writerBrief: string
}

const TAHI_BLOG_BASE = 'https://www.tahi.studio'

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80)
}

/** Build the live URL for a topic. `urlOverride` wins (used for the
 *  "boost the bad ones" workflow where we already know the URL).
 *  Otherwise we predict /resources/glossary/{slug} for glossary, /blog/
 *  {slug} for blog. */
function resolveTargetUrl(topic: string, contentType: 'glossary' | 'blog', urlOverride: string | null): string {
  if (urlOverride) return urlOverride
  return contentType === 'glossary'
    ? `${TAHI_BLOG_BASE}/resources/glossary/${slugify(topic)}`
    : `${TAHI_BLOG_BASE}/blog/${slugify(topic)}`
}

function isoDaysAgo(n: number): string {
  const d = new Date()
  d.setUTCDate(d.getUTCDate() - n)
  return d.toISOString().slice(0, 10)
}

export async function fetchSeoSignals(
  database: Database,
  topic: string,
  contentType: 'glossary' | 'blog',
  urlOverride: string | null = null,
): Promise<SeoSignals> {
  const url = resolveTargetUrl(topic, contentType, urlOverride)
  const signals: SeoSignals = {
    topic,
    url,
    gsc: { available: false, clicks7d: null, impressions7d: null, avgPosition7d: null, clicks30d: null, impressions30d: null, avgPosition30d: null, indexStatus: null, lastCrawlTime: null, topQueries: [] },
    ga4: { available: false, sessions30d: null, engagedSessions30d: null, avgSessionDuration: null },
    seRanking: { available: false, targetKeyword: null, currentPosition: null, searchVolume: null, difficulty: null, competitorTopUrls: [], note: 'SE Ranking integration not yet wired (no SE_RANKING_API_KEY env)' },
    writerBrief: '',
  }

  // ── GSC ────────────────────────────────────────────────────────────
  try {
    const tokens = await getGoogleAccessToken(database)
    const sites = await listGscSites(tokens.accessToken)
    const site = resolveGscPropertyForUrl(`${TAHI_BLOG_BASE}/`, sites)
    if (site) {
      const filter = [{ filters: [{ dimension: 'page', operator: 'equals', expression: url }] }]
      const endDate = isoDaysAgo(1)
      // Trailing 7d + 30d
      const [rows7, rows30, topQ] = await Promise.allSettled([
        searchAnalytics(tokens.accessToken, site.siteUrl, { startDate: isoDaysAgo(7), endDate, dimensions: ['date'], dimensionFilterGroups: filter }),
        searchAnalytics(tokens.accessToken, site.siteUrl, { startDate: isoDaysAgo(30), endDate, dimensions: ['date'], dimensionFilterGroups: filter }),
        searchAnalytics(tokens.accessToken, site.siteUrl, { startDate: isoDaysAgo(30), endDate, dimensions: ['query'], dimensionFilterGroups: filter, rowLimit: 10 }),
      ])
      const sum = (rows: Array<{ clicks: number; impressions: number; position: number }>) => rows.reduce(
        (a, r) => ({ clicks: a.clicks + r.clicks, impressions: a.impressions + r.impressions, position: a.position + r.position * r.impressions }),
        { clicks: 0, impressions: 0, position: 0 },
      )
      if (rows7.status === 'fulfilled') {
        const s = sum(rows7.value)
        signals.gsc.clicks7d = s.clicks
        signals.gsc.impressions7d = s.impressions
        signals.gsc.avgPosition7d = s.impressions > 0 ? Math.round((s.position / s.impressions) * 10) / 10 : null
      }
      if (rows30.status === 'fulfilled') {
        const s = sum(rows30.value)
        signals.gsc.clicks30d = s.clicks
        signals.gsc.impressions30d = s.impressions
        signals.gsc.avgPosition30d = s.impressions > 0 ? Math.round((s.position / s.impressions) * 10) / 10 : null
      }
      if (topQ.status === 'fulfilled') {
        signals.gsc.topQueries = topQ.value
          .map(r => ({
            query: (r as unknown as { keys?: string[] }).keys?.[0] ?? '',
            clicks: r.clicks,
            impressions: r.impressions,
            position: Math.round(r.position * 10) / 10,
          }))
          .filter(q => q.query)
      }
      // URL inspection — index status
      try {
        const ins = await inspectUrl(tokens.accessToken, url, site.siteUrl)
        signals.gsc.indexStatus = ins.indexStatus ?? null
        signals.gsc.lastCrawlTime = ins.lastCrawlTime ?? null
      } catch { /* skip */ }
      signals.gsc.available = true
    }
  } catch { /* GSC unavailable — leave defaults */ }

  // ── GA4 ────────────────────────────────────────────────────────────
  try {
    const [ga4Row] = await database
      .select({ value: schema.settings.value })
      .from(schema.settings)
      .where(eq(schema.settings.key, 'ga4.propertyId'))
      .limit(1)
    const ga4PropertyId = ga4Row?.value
    if (ga4PropertyId) {
      const tokens = await getGoogleAccessToken(database)
      const pagePath = new URL(url).pathname
      const rows = await runGa4Report(tokens.accessToken, ga4PropertyId, {
        startDate: isoDaysAgo(30),
        endDate: isoDaysAgo(1),
        dimensions: ['pagePath'],
        metrics: ['sessions', 'engagedSessions', 'averageSessionDuration'],
      })
      const match = rows.find(r => r.dimensionValues[0]?.value === pagePath)
      if (match) {
        signals.ga4.sessions30d = Number(match.metricValues[0]?.value) || 0
        signals.ga4.engagedSessions30d = Number(match.metricValues[1]?.value) || 0
        signals.ga4.avgSessionDuration = Number(match.metricValues[2]?.value) || 0
      } else {
        signals.ga4.sessions30d = 0
        signals.ga4.engagedSessions30d = 0
        signals.ga4.avgSessionDuration = 0
      }
      signals.ga4.available = true
    }
  } catch { /* GA4 unavailable */ }

  // ── SE Ranking ─────────────────────────────────────────────────────
  // SE Ranking REST API requires an API token + project setup. Wiring
  // it requires a config-time step (Liam: set SE_RANKING_API_KEY +
  // SE_RANKING_PROJECT_ID in Webflow Cloud env). For now this is a
  // best-effort stub that hits SE Ranking only when configured.
  const seRankingKey = process.env.SE_RANKING_API_KEY
  const seRankingProjectId = process.env.SE_RANKING_PROJECT_ID
  if (seRankingKey && seRankingProjectId) {
    try {
      // SE Ranking's API has multiple endpoints; this hits the keyword-
      // metrics endpoint for the primary keyword (defaults to topic).
      // Docs: https://seranking.com/api-data.html
      const kw = topic
      const res = await fetch(`https://api.seranking.com/research/keywords?keyword=${encodeURIComponent(kw)}&engine=us`, {
        headers: { Authorization: `Token ${seRankingKey}` },
        signal: AbortSignal.timeout(8000),
      })
      if (res.ok) {
        const data = await res.json() as { volume?: number; difficulty?: number; results?: Array<{ url: string; title: string }> }
        signals.seRanking.targetKeyword = kw
        signals.seRanking.searchVolume = data.volume ?? null
        signals.seRanking.difficulty = data.difficulty ?? null
        signals.seRanking.competitorTopUrls = (data.results ?? []).slice(0, 5)
        signals.seRanking.note = 'SE Ranking keyword research API'
        signals.seRanking.available = true
      } else {
        signals.seRanking.note = `SE Ranking returned HTTP ${res.status}`
      }
    } catch (err) {
      signals.seRanking.note = `SE Ranking fetch failed: ${err instanceof Error ? err.message.slice(0, 60) : 'unknown'}`
    }
  }

  // ── Compose the writer brief ───────────────────────────────────────
  signals.writerBrief = composeWriterBrief(signals)
  return signals
}

function composeWriterBrief(s: SeoSignals): string {
  const lines: string[] = []
  lines.push(`# SEO competitive intelligence: "${s.topic}"`)
  lines.push(`Target URL: ${s.url}`)
  lines.push('')

  // GSC section
  if (s.gsc.available) {
    lines.push('## Current Google Search Console (this URL)')
    lines.push(`- Index status: ${s.gsc.indexStatus ?? 'unknown'}`)
    lines.push(`- Last crawl: ${s.gsc.lastCrawlTime ?? 'never'}`)
    lines.push(`- Last 7 days: ${s.gsc.clicks7d ?? 0} clicks · ${s.gsc.impressions7d ?? 0} impressions · pos ${s.gsc.avgPosition7d ?? 'n/a'}`)
    lines.push(`- Last 30 days: ${s.gsc.clicks30d ?? 0} clicks · ${s.gsc.impressions30d ?? 0} impressions · pos ${s.gsc.avgPosition30d ?? 'n/a'}`)
    if (s.gsc.topQueries.length > 0) {
      lines.push('')
      lines.push('Top 10 queries currently earning impressions for this URL (rewrite MUST cover all of these explicitly):')
      for (const q of s.gsc.topQueries) {
        lines.push(`  - "${q.query}" → ${q.clicks} clicks / ${q.impressions} impressions / pos ${q.position}`)
      }
    } else {
      lines.push('- Top queries: (none yet — either unindexed or no impressions in last 30d)')
    }
    lines.push('')
  } else {
    lines.push('## Google Search Console')
    lines.push('- Unavailable (Google not connected or auth expired)')
    lines.push('')
  }

  // GA4 section
  if (s.ga4.available && s.ga4.sessions30d != null) {
    lines.push('## Current Google Analytics (this URL, last 30 days)')
    lines.push(`- Sessions: ${s.ga4.sessions30d}`)
    lines.push(`- Engaged sessions: ${s.ga4.engagedSessions30d ?? 0}`)
    lines.push(`- Avg session duration: ${s.ga4.avgSessionDuration != null ? Math.round(s.ga4.avgSessionDuration) + 's' : 'n/a'}`)
    lines.push('')
  }

  // SE Ranking
  if (s.seRanking.available) {
    lines.push('## SE Ranking competitive landscape')
    lines.push(`- Keyword: ${s.seRanking.targetKeyword}`)
    lines.push(`- Search volume: ${s.seRanking.searchVolume ?? 'n/a'}`)
    lines.push(`- Keyword difficulty: ${s.seRanking.difficulty ?? 'n/a'}`)
    if (s.seRanking.competitorTopUrls.length > 0) {
      lines.push('Top competitors currently ranking:')
      for (const c of s.seRanking.competitorTopUrls) {
        lines.push(`  - ${c.title} (${c.url})`)
      }
    }
    lines.push('')
  } else if (s.seRanking.note) {
    lines.push(`## SE Ranking: ${s.seRanking.note}`)
    lines.push('')
  }

  // Directive
  lines.push('## How to use this brief')
  lines.push('- If queries are showing impressions but no clicks, the title + meta description need stronger hooks.')
  lines.push('- If position is 11-20, the body needs more specificity + internal links to escape page 2.')
  lines.push('- If indexStatus is NOT_INDEXED, the body needs more depth + at least 5-8 contextual internal links from already-indexed pages.')
  lines.push('- If competitor URLs are listed, your version MUST cover what they cover + add 1 genuinely net-new claim.')
  lines.push('- Use the top queries verbatim as H2 headings where they make sense — "people search this exact phrase".')

  return lines.join('\n')
}

// ── Bulk variant: rank all glossary URLs by underperformance ──────────

export interface UnderperformingItem {
  itemId: string
  slug: string
  term: string
  url: string
  impressions30d: number
  clicks30d: number
  avgPosition30d: number | null
  ctr: number              // clicks / impressions
  underperformanceScore: number  // higher = more in need of rewrite
  reason: string
  indexStatus: string | null
}

export interface UnderperformerRanking {
  scanned: number
  underperformers: UnderperformingItem[]
  unindexedItems: UnderperformingItem[]
  durationMs: number
}

/** Pull all glossary items from post_scorecards (or fall back to live
 *  GSC if scorecards haven't synced yet), score them by a composite
 *  "needs rewrite" metric, return top N. */
export async function rankUnderperformingItems(
  database: Database,
  contentType: 'glossary' | 'blog',
  topN: number = 20,
): Promise<UnderperformerRanking> {
  const t0 = Date.now()
  const result: UnderperformerRanking = {
    scanned: 0,
    underperformers: [],
    unindexedItems: [],
    durationMs: 0,
  }

  // Pull from post_scorecards table (populated by the weekly cron).
  const rows = await database
    .select({
      webflowItemId: schema.postScorecards.webflowItemId,
      url: schema.postScorecards.url,
      gscIndexStatus: schema.postScorecards.gscIndexStatus,
      gscImpressions30d: schema.postScorecards.gscImpressions30d,
      gscClicks30d: schema.postScorecards.gscClicks30d,
      gscAvgPosition30d: schema.postScorecards.gscAvgPosition30d,
    })
    .from(schema.postScorecards)
    .limit(500)

  const filtered = rows.filter(r => {
    if (!r.url) return false
    if (contentType === 'glossary') return r.url.includes('/resources/glossary/')
    return r.url.includes('/blog/')
  })
  result.scanned = filtered.length

  const items: UnderperformingItem[] = []
  for (const r of filtered) {
    const url = r.url!
    const slug = url.split('/').filter(Boolean).pop() ?? ''
    const term = slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    const impressions = r.gscImpressions30d ?? 0
    const clicks = r.gscClicks30d ?? 0
    const pos = r.gscAvgPosition30d != null ? r.gscAvgPosition30d / 100 : null  // stored ×100
    const ctr = impressions > 0 ? clicks / impressions : 0

    // Underperformance scoring: high impressions + low clicks + bad
    // position = highest priority. NOT_INDEXED items go to a separate
    // bucket because they need indexing, not rewriting.
    if (r.gscIndexStatus && r.gscIndexStatus !== 'INDEXING_ALLOWED' && r.gscIndexStatus !== 'PASS') {
      items.push({
        itemId: r.webflowItemId ?? '',
        slug, term, url,
        impressions30d: impressions, clicks30d: clicks, avgPosition30d: pos, ctr,
        underperformanceScore: impressions,
        reason: `Not indexed (${r.gscIndexStatus})`,
        indexStatus: r.gscIndexStatus,
      })
      continue
    }

    let score = 0
    let reason = ''
    // 1) High impressions + position 11-30 = "almost there, push to page 1"
    if (impressions >= 50 && pos != null && pos >= 11 && pos <= 30) {
      score = impressions * (30 - pos)
      reason = `Position ${pos.toFixed(1)} with ${impressions} impressions — close to page 1, needs depth`
    }
    // 2) Position 1-10 but low CTR = title/meta needs work
    else if (impressions >= 100 && pos != null && pos <= 10 && ctr < 0.02) {
      score = impressions * 0.5
      reason = `Ranking pos ${pos.toFixed(1)} but ${(ctr * 100).toFixed(1)}% CTR — title/meta weak`
    }
    // 3) Position >30 with impressions = content too thin
    else if (impressions >= 30 && pos != null && pos > 30) {
      score = impressions * 0.3
      reason = `Position ${pos.toFixed(1)} with ${impressions} impressions — content needs rewrite`
    }
    // 4) No impressions at all = not in search at all (different problem,
    //    handle in indexing reverser not rewriter)
    else {
      continue
    }

    items.push({
      itemId: r.webflowItemId ?? '',
      slug, term, url,
      impressions30d: impressions, clicks30d: clicks, avgPosition30d: pos, ctr,
      underperformanceScore: score,
      reason,
      indexStatus: r.gscIndexStatus,
    })
  }

  // Split into unindexed (for IndexNow workflow) vs underperformers
  // (for Tier 3 rewrite).
  result.unindexedItems = items.filter(i => i.reason.startsWith('Not indexed'))
  result.underperformers = items
    .filter(i => !i.reason.startsWith('Not indexed'))
    .sort((a, b) => b.underperformanceScore - a.underperformanceScore)
    .slice(0, topN)

  result.durationMs = Date.now() - t0
  return result
}
